name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/patr_db
      REDIS_URL: redis://localhost:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Start PostgreSQL with Docker
        run: |
          docker run -d --name postgres \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -e POSTGRES_DB=patr_db \
            -p 5432:5432 \
            postgres:latest
          sleep 10 # Wait for PostgreSQL to start

      - name: Start Redis with Docker
        run: |
          docker run -d --name redis \
            -p 6379:6379 \
            redis:latest
          sleep 5 # Wait for Redis to start

      - name: Install cargo-leptos
        run: cargo install cargo-leptos

      - name: Build project
        run: cargo leptos build

      - name: Run tests
        run: cargo test
